### ISSUE TITLE
Is new adoption recommended?

### ISSUE THREAD

**Issue by ThomasGHenry** [danger/danger-js#1059]
Hey, folks! 

I know this is a borderline jerk question to be raising, but I have 3 intentions here. 

First, I sincerely want to gauge your expectations for this project in order to avoid investing time in something that's soon to be defunct. (Maybe this was a great idea that has run its course and exists now more for the established users than newcomers. There's no shame in that, but personally I might need to look elsewhere.) 

Second, I want to call to your attention that the official plugin listing might need some pruning if everything is actually fine and you want to avoid giving the impression that I'm getting. 

Third, I want to have this discussion in public for the benefit of anyone with similar concerns whether the future is sunglasses emoji or otherwise.

Anyway, the meat of it is this. I was excited to try this tool, but the state of the plugin ecosystem has me wondering about the future of the project. I tried a handful of plugins so far, most if not all from the main dangerjs page, and I think only one actually worked (jest and only sort of). The flow plugin repo is archived with no indication of an alternative. The eslint plugin hasn't been touched in years. Among others, I see broken image links, empty descriptions, and other indications of abandonment.

Should I be investing time in learning how to use this?

Thanks for understanding and good luck!

**Comment by orta** [comment]
Danger JS isn't abandoned, it's used on things like React and TypeScript - plugins are useful but non-essential for getting things done given that you're supposed to be writing your own rules and not arbitrarily C&Ping them from others.

The plugin listing is totally auto-generated from people including the tag on npm, I know the ones I use still work but folks might not have the time to maintain stuff and that's just OSS really.

**Comment by fbartho** [comment]
@ThomasGHenry -- Did you look at the releases list or issue / pull-request history? -- This is a pretty healthy (but mature) ecosystem. Releases happen regularly, and generally issues are raised/discussed and many feature requests are implemented.

That said, the plugin ecosystem is definitely a little uneven in quality / health. The trick here is that much of what you can do with DangerJS is really specific to your project/team, so much of the code doesn't end up being usable as a plugin!

My list of plugins includes:
- danger-plugin-jest
- danger-plugin-yarn
- for eslint, I've recently forked one of the [older forks](https://www.npmjs.com/package/@seadub/danger-plugin-eslint) of the eslint plugin (mine: [@fbartho/danger-plugin-eslint](https://github.com/fbartho/danger-plugin-eslint)), because I needed to build a very team-specific feature for one project, and then on another project we started moving to a monorepo and the default plugin needed to learn how to remap paths -- I haven't gotten around to finishing cleanup to contribute that back.

After that, I've written a bunch of Dangerfiles for different project that implement custom behavior like
A. don't block a PR for lint issues on lines you didn't edit, but still publish the issues
B. Automatically Add/Remove labels based on review status, or other considerations
C. Hit our CI's API, and collect links to particular build-artifacts (iOS/Android builds), that way you get a table of builds that you can directly install if you open the PR on your device.

**Comment by f-meloni** [comment]
Danger-js is not only not abandoned, but is also powering the Python, Swift and Kotlin Danger versions, that are quite young but have already a good adoption in the open-source and enterprise world.

**Comment by ThomasGHenry** [comment]
Thanks, all! I'm very glad to hear this. I love the concept. I'll steer clear of the plugins and start getting my hands dirty.
