### ISSUE TITLE
Question: Displaying a SVG File in Danger.js message

### ISSUE THREAD

**Issue by fathshalaby** [danger/danger-js#1288]
How do I add a svg image to the message.

I have a plot that I generate and save as .svg file and would like to display it as a message in danger.js. What would be the best approach for that.

**Comment by orta** [comment]
Upload it ( [likely](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) the CI has a way to attach artefacts to runs ) and then show it like you would in a normal comment

**Comment by amadeu01** [comment]
@orta do you have any example ? I don't know any sort of public link for github atifacts to be able to use as in comments.
I've only seen this kind of option https://docs.github.com/en/rest/actions/artifacts watch should basically fetch the artifact from github, but not use the image/svg.

**Comment by orta** [comment]
For Artsy, we would upload image snapshots to S3 on CI and then show those, I've never done it with the GitHub Actions API - it was an example, perhaps that's not possible

**Comment by fbartho** [comment]
I ended up uploading such assets to an Orphan Branch in my repo, so then I can use Github to reference the image across branches in comments and in README files.

I don't use GitHub's Artifacts functionality for this, because I couldn't figure out how to reference the artifacts in a way that allowed me to show them in a README.md -- though I think it's possible to show them just in a comment.
