### ISSUE TITLE
Investigate Danger for synchronous methods

### ISSUE THREAD

**Issue by orta** [danger/danger-js#233]
When running Danger inside Peril, it's very likely that any blocking call is going to cause pretty serious issues over the long run. So Danger will need any `xxSync` functions converted to the `xx` version.

**Comment by orta** [comment]
As a part of this PR, it's worth looking at whether tslint can lint for this too, or if we should make a Danger rule.

**Comment by deecewan** [comment]
Is this talking about in a Dangerfile?

I think this would be okay, as all the `xx` methods have the same (? very similar?) patterns. A naive way to approach this would be to replace it, copy in all the code after into a callback, and set the `data` param in the callback to the variable name.

There are multiple problems with this, tho. The sync functions can be used just about everywhere as a value.

Additionally, an issue with my initial solution is this:

```js
(function() {
    function testFn() {
        console.log(i);
    }
    testFn();
    var i = 10;
    testFn();
})()
```

This outputs:

```
undefined
10
```

because a `var` declaration is hoisted to the top of the function, and exists as `undefined` until it's assigned a value. but `testFn` always refers to the same `var` so it will be updated.

Another potential solution I just thought of would be to wrap the entire dangerfile like:

```
(async function() {
  /* Dangerfile content goes here */
})()
```

and then replace all the `xxSync` methods with Promisified versions. Like:

```js
function doThing(file) {
   console.log(file);
}

/* old */
doThing(fs.readFileSync('./test.txt'))

/* new */
doThing(await fsPromise.readFile('./test.txt'))
```

Obviously `fsPromise` is not a thing. I made it up. But these methods are very easy to wrap, or there are a bunch of libraries that already do it.

To wrap:

```js
function promisify(fn) {
  return (...args) => {
		return new Promise((resolve, reject) => {
    	fn(...args, (err, result) => {
      	if (err) {
        	return reject(err);
        }
        return resolve(result);
      });
    });
  };
}
```

And that will wrap all of the node functions with the `(error, result)` callback style.

This ended up a lot longer than I expected. Just kept having thoughts as I was writing.

**Comment by deecewan** [comment]
Oh wow. I am now seeing that you probably meant any internal methods that use `xxSync` need to be converted to `xx`. Not external Dangerfiles.

**Comment by orta** [comment]
Ah yeah, afraid so - the artsy site was taking some serious downtime due to one sync call in all our node app, took a long time to find it - wanted to try get that sorted before it became an issue

**Comment by macklinu** [comment]
Ran `ack Sync source --break --heading` locally - here's where Sync is found in the codebase:

```
source/ci_source/get_ci_source.ts
29:    const exist = fs.statSync(path).isFile()

source/commands/danger-pr.ts
52:    stat = fs.statSync(filePath)

source/commands/danger-run.ts
77:        const stat = fs.statSync(dangerFile)

source/commands/utils/_tests/file-utils.test.ts
3:  return { existsSync: p => p === mockDangerfilePath }

source/commands/utils/file-utils.ts
1:import { existsSync } from "fs"
13:  if (existsSync("dangerfile.ts")) {
16:  if (existsSync("dangerfile.js")) {

source/platforms/_tests/_github.test.ts
2:import { readFileSync } from "fs"
8:  Promise.resolve(JSON.parse(readFileSync(`${fixtures}/${path}`, {}).toString()))

source/platforms/github/_tests/_github_git.test.ts
6:import { readFileSync } from "fs"
14:  Promise.resolve(JSON.parse(readFileSync(pathJoin(fixtures, path), {}).toString()))
18:  Promise.resolve(readFileSync(pathJoin(fixtures, path), {}).toString())
30:const masterSHA = JSON.parse(readFileSync(pathJoin(fixtures, pullRequestInfoFilename), {}).toString()).base.sha

source/platforms/github/_tests/_github_utils.test.ts
3:import { readFileSync } from "fs"
7:const fixuredData = path => JSON.parse(readFileSync(`${fixtures}/${path}`, {}).toString())

source/runner/_tests/_danger_runner.test.ts
154:    fs.writeFileSync(path, "import { danger, warn, fail, message } from 'danger'")
156:    expect(fs.readFileSync(path).toString()).toEqual("// Removed import")

source/runner/DangerfileRunner.ts
132:  const originalContents = fs.readFileSync(filename).toString()
137:  if (originalContents !== fs.readFileSync(filename).toString()) {
138:    fs.writeFileSync(filename, originalContents)
148:  const contents = fs.readFileSync(filename).toString()
151:    fs.writeFileSync(filename, cleanDangerfile(contents))

```

**Comment by orta** [comment]
I feel like `source/ci_source/get_ci_source.ts` and `source/runner/DangerfileRunner.ts` will be the only ones we'll care about in those cases 👍 

thanks
