### ISSUE TITLE
`danger local` does absolutely nothing for me

### ISSUE THREAD

**Issue by cactysman** [danger/danger-js#631]
Hello there!

I tried setting up Danger to run a few checks locally to eventually use it as a git hook or something alike.

When I try running `danger local` on following dangerfile:
```js
const danger = require('danger');
console.log(danger.git);
```
... then it just does nothing, no matter if I have a dangerfile, specify one, if it's faulty or whatever.

I tried running danger 3.7.20 in a git repository on both Windows 10 and Debian 9 with NodeJS 9.

Am I missing anything? I tried looking at the docs and the PR and issues that are related to this topic but I can't see anything wrong 🤔

**Comment by metaa** [comment]
I'd totally love to use this, but it's just broken.

1. When trying to use it at work, it breaks because the method used to get the previous commits contains spaces in the [format string](https://git-scm.com/docs/pretty-formats).
1. When trying to run it at home, it breaks with `Unknown stdin file type` and random `concat` errors.

I looked at the code for git operations and it just creeps me out.
I'd love to help if anyone is even interested in getting this to work for local projects, but right now it doesn't look like it matters to anyone at all.

**Comment by orta** [comment]
I use this feature in a bunch of repos daily, so it's definitely working for me regularly - would love to see fixes for windows issues 👍

**Comment by metaa** [comment]
I see, it apparently is a problem with NodeJS on WSL (the fist time ever something didn't work on WSL for me 🤔), I don't think there's much we can do unless someone fixes NodeJS here.
